package com.example.maximeglod.fbta;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;


import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;
import android.widget.ListView;
import android.widget.Toast;
import java.util.ArrayList;
import java.util.List;

public class MainAliments extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_aliments);


        List<Aliments> image_details = getListData();
        final GridView gridView = (GridView) findViewById(R.id.gridView);
        gridView.setAdapter(new CustomGridAdapter(this, image_details));

        // Quand l'utilisateur clique sur un élément de la grid view
        gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> a, View v, int position, long id) {
                Object o = gridView.getItemAtPosition(position);
                Aliments aliments = (Aliments) o;
                Toast.makeText(MainAliments.this, "Selection :"
                        + " " + aliments, Toast.LENGTH_LONG).show();
            }
        });
    }

    private List<Aliments> getListData() {
        List<Aliments> list = new ArrayList<Aliments>();
        Aliments ail = new Aliments("Ail", "ail", 5);
        Aliments ailenpoudre = new Aliments("Ail en poudre", "ailenpoudre", 333);
        Aliments amendesblanchiessechees = new Aliments("Amandes Blanchies Séchées", "amandesblanchiessechees",586);
        Aliments amandessechees = new Aliments("Amandes séchées","amandessechees",589);
        Aliments anethfraiche = new Aliments("Aneth Fraiche","anethfraiche",43);
        Aliments anethsechee = new Aliments("Aneth Séchée","anethsechee",253);
        Aliments aromedevanille = new Aliments("Arome de Vanille","aromedevanille",56);
        Aliments aromedevanillealcool = new Aliments("Arome de Vanille Alcoolisé","aromedevanillealcool",237);
        Aliments asperges = new Aliments("Asperges","asperges",28);
        Aliments aubergine = new Aliments("Aubergine","aubergine",29);
        Aliments avocat = new Aliments("Avocat","avocat",208);
        Aliments bacon = new Aliments("Bacon","bacon",270);
        Aliments baguette = new Aliments("Baguette","baguette",638);
        Aliments banane = new Aliments("Banane","banane",100);
        Aliments bananesechee = new Aliments("Banane Séchées","bananesechee",292);
        Aliments barloup = new Aliments("Bar Loup","barloup",98);
        Aliments basilicfrais = new Aliments("Basilic Frais","basilicfrais",27);
        Aliments basilicfinesherbes = new Aliments("Basilic Fines Herbes","basilicfinesherbes",251);
        Aliments betaselen = new Aliments("Betaselen","betaselen",0);
        Aliments betteraverouge = new Aliments("Betterave Rouge","betteraverouge",41);
        Aliments beurre = new Aliments("Beurre","beurre",741);
        Aliments biereblonde = new Aliments("Biere Blonde","biereblonde",146);
        Aliments biereordinaire = new Aliments("Biere Ordinaire","biereordinaire",33);
        Aliments bifteckboeuf = new Aliments("Bifteck de Boeuf","bifteckboeuf",174);
        Aliments bifteckcheval = new Aliments("Bifteck de Cheval","bifteckcheval",123);
        Aliments bigmac = new Aliments("BigMac","bigmac",559);
        Aliments bigorneau = new Aliments("Bigorneau","bigorneau",101);
        Aliments biscotte = new Aliments("Biscotte","biscotte",411);
        Aliments biscuitsable = new Aliments("Biscuit Sablé","biscuitsable",457);
        Aliments blancdepoulet = new Aliments("Blanc de Poulet","blancdepoulet",142);
        Aliments blancdoeuf = new Aliments("Blanc d'Oeuf","blancdoeuf",49);
        Aliments boudinblanc = new Aliments("Boudin Blanc","boudinblanc",330);
        Aliments boudinnoir = new Aliments("Boudin Noir","boudinnoir",439);
        Aliments bouillondevolaille = new Aliments("Bouillon de Volaille","bouillondevolaille",307);
        Aliments brie = new Aliments("Brie","brie",10);
        Aliments brochet = new Aliments("Brochet","brochet",10);
        Aliments cabillaud = new Aliments("Cabillaud","cabillaud",10);
        Aliments cacahuettes = new Aliments("Cacahuettes","cacahuettes",10);
        Aliments cafefiltre = new Aliments("Café Filtré","cafefiltre",10);
        Aliments cafenescafe = new Aliments("Café Nescafé","cafenescafe",10);
        Aliments cafenescafe1tasse = new Aliments("Café Nescafé 1 Tasse","cafenescafe1tasse",10);
        Aliments caille = new Aliments("Caille","caille",10);
        Aliments cake = new Aliments("Cake","cake",10);
        Aliments calamarfrit = new Aliments("Calamar Frit","calamarfrit",10);
        Aliments camambert = new Aliments("Camambert","camambert",10);
        Aliments canardroti = new Aliments("Canard Roti","canardroti",10);
        Aliments cannelle = new Aliments("Cannelle","cannelle",10);
        Aliments capresenboite = new Aliments("Capres en Boite","capresenboite",10);
        Aliments cardamome = new Aliments("Cardamome","cardamome",10);
        Aliments carencyl = new Aliments("Carencyl","carencyl",10);
        Aliments carotte = new Aliments("Carotte","carotte",10);
        Aliments carpe = new Aliments("Carpe","carpe",10);
        Aliments carrelet = new Aliments("Carrelet","carrelet",10);
        Aliments casis = new Aliments("Casis","casis",10);
        Aliments caviar = new Aliments("Caviar","caviar",10);
        Aliments celerifeuille = new Aliments("Celeri en Feuille","celerifeuille",10);
        Aliments celeriracine = new Aliments("Celeri en Racine","celeriracine",10);
        Aliments cerealescropsyfruit = new Aliments("Céréales Cropsy Fruit","cerealescropsyfruit",10);
        Aliments cerealesnature = new Aliments("Céréales Nature","cerealesnature",10);
        Aliments cerfeuille = new Aliments("Cerfeuille","cerfeuille",10);
        Aliments cerises = new Aliments("cerises","cerises",10);
        Aliments chairasaucisse = new Aliments("Chair à Saucisse","chairasaucisse",10);
        Aliments champagne = new Aliments("Champagne","champagne",10);
        Aliments champignons = new Aliments("Champignons","champignons",10);
        Aliments charlottegateau = new Aliments("Charlotte","charlottegateau",10);
        Aliments chataignefraiche = new Aliments("Chataigne Fraiche","chataignefraiche",10);
        Aliments chevalroti = new Aliments("Cheval Roti","chevalroti",10);
        Aliments chocapic = new Aliments("Chocapic","chocapic",10);
        Aliments chocolatacroquer = new Aliments("Chocolat à Croquer","chocolatacroquer",10);
        Aliments chocolataulait = new Aliments("Chocolat au Lait","chocolataulait",10);
        Aliments chocolatenpoudre = new Aliments("Chocolat en Poudre","chocolatenpoudre",10);
        Aliments choucroutte = new Aliments("Choucroutte","choucroutte",10);
        Aliments choucru = new Aliments("Chou Cru","choucru",10);
        Aliments choufleur = new Aliments("Choufleur","choufleur",10);
        Aliments chouxdebruxelles = new Aliments("Choux De Bruxelles","chouxdebruxelles",10);
        Aliments chrome = new Aliments("Chrome","chrome",10);
        Aliments ciboulettecrue = new Aliments("Ciboulette Crue","ciboulettecrue",10);
        Aliments ciboulettelyophilisee = new Aliments("Ciboulette Lyophiliseee","ciboulettelyophilisee",10);
        Aliments citronjaune = new Aliments("Citron Jaune","citronjaune",10);
        Aliments citronvert = new Aliments("Citron Vert","citronvert",10);
        Aliments citrouille = new Aliments("Citrouille","citrouille",10);
        Aliments clousdegirofle = new Aliments("Clous de Girofle","clousdegirofle",10);
        Aliments calamarnature = new Aliments("Calamar Nature","calmarnature",10);
        Aliments cocacola = new Aliments("Coca-Cola","cocacola",10);
        Aliments cocacolacanette = new Aliments("Coca-Cola Canette","cocacolacanette",10);
        Aliments coeurdeboeuf = new Aliments("Coeur De Boeuf","coeurdeboeuf",10);
        Aliments coing = new Aliments("Coing","coing",10);
        Aliments colinmerlu = new Aliments("Colin Merlu","colinmerlu",10);
        Aliments concombre = new Aliments("Concombre","concombre",10);
        Aliments coneglacecreme = new Aliments("Cone glace creme","coneglacecreme",10);
        Aliments confiture = new Aliments("Confiture","confiture",10);
        Aliments congrepoisson = new Aliments("Congre Poisson","congrepoisson",10);
        Aliments contrexeville = new Aliments("Contrexe Ville","contrexeville",10);
        Aliments coquillestjacques = new Aliments("Coquilles ST-Jacques","coquillestjacques",10);
        Aliments cornflakes = new Aliments("Cornflakes","cornflakes",10);
        Aliments cornichon = new Aliments("Cornichon","cornichon",10);
        Aliments cotedagneau = new Aliments("Cote d'Agneau","cotedagneau",10);
        Aliments cotedeboeufrotie = new Aliments("cotede boeuf rotie","cotedeboeufrotie",10);
        Aliments cotelettedeporc = new Aliments("cotelette de porc","cotelettedeporc",10);
        Aliments courgettes = new Aliments("courgettes","courgettes",10);
        Aliments couscous = new Aliments("couscous","couscous",10);
        Aliments crabechair = new Aliments("crabe chair","crabechair",10);
        Aliments cremechantilly = new Aliments("creme chantilly","cremechantilly",10);
        Aliments cremedasperges = new Aliments("creme d'Asperges","cremedasperges",10);
        Aliments cremefraiche = new Aliments("creme fraiche","cremefraiche",10);
        Aliments cresson = new Aliments("cresson","cresson",10);
        Aliments crevette = new Aliments("crevette","crevette",10);
        Aliments croissant = new Aliments("croissant","croissant",10);
        Aliments cuissedegrnouille = new Aliments("cuisse de grnouille","cuissedegrnouille",10);
        Aliments cuissepouletroti = new Aliments("cuissepouletroti","cuissepouletroti",10);
        Aliments cumin = new Aliments("cumin","cumin",10);
        Aliments curry = new Aliments("curry","curry",10);
        Aliments daiquiri = new Aliments("daiquiri","daiquiri",10);
        Aliments dattes = new Aliments("dattes","dattes",10);
        Aliments dorade = new Aliments("dorade","dorade",10);
        Aliments echalote = new Aliments("echalote","echalote",10);
        Aliments echalotelyophilisees = new Aliments("echalotelyophilisees","echalotelyophilisees",10);
        Aliments echalotes = new Aliments("Echalotes","echalotes",10);
        Aliments eclairgateau = new Aliments("Eclair","eclairgateau",10);
        Aliments ecrevisse = new Aliments("Ecrevisse","ecrevisse",10);
        Aliments endives = new Aliments("Endives","endives",10);
        Aliments epauleagneaurotie = new Aliments("Epaule d'Agneau Rotie","epauleagneaurotie",10);
        Aliments epinard = new Aliments("Epinard","epinard",10);
        Aliments escalopededinde = new Aliments("Escalope De Dinde","escalopededinde",10);
        Aliments escalopedeveau = new Aliments("Escalope De Veau","escalopedeveau",10);
        Aliments escargot = new Aliments("Escargot","escargot",10);
        Aliments espadon = new Aliments("Espadon","espadon",10);
        Aliments estragon = new Aliments("Estragon","estragon",10);
        Aliments esturgeon = new Aliments("Esturgeon","esturgeon",10);
        Aliments evian = new Aliments("Evian","evian",10);
        Aliments extraitdevanille = new Aliments("Extrait de vanille","extraitdevanille",10);
        Aliments faisan = new Aliments("Faisan","faisan",10);
        Aliments farinedeble = new Aliments("Farine de ble","farinedeble",10);
        Aliments fauxfilet = new Aliments("Faux filet","fauxfilet",10);
        Aliments fenouil = new Aliments("Fenouil","fenouil",10);
        Aliments feuilledecoriandre = new Aliments("feuille de coriandre","feuilledecoriandre",10);
        Aliments feuilledelorier = new Aliments("Feuille de lorier","feuilledelorier",10);
        Aliments feveseche = new Aliments("Fève seche","feveseche",10);
        Aliments figuesseches = new Aliments("Figues seches","figuesseches",10);
        Aliments filetdeboeuf = new Aliments("Filet de boeuf","filetdeboeuf",10);
        Aliments filetmaquerau = new Aliments("Filet maquerau","filetmaquerau",10);
        Aliments fletan = new Aliments("Fletan","fletan",10);
        Aliments floconsdavoine = new Aliments("Flocons d'avoine","floconsdavoine",10);
        Aliments foiedeveau = new Aliments("Foie de veau","foiedeveau",10);
        Aliments foiegras = new Aliments("Foie gras","foiegras",10);
        Aliments fraise = new Aliments("Fraise","fraise",10);
        Aliments frites = new Aliments("Frites","frites",10);
        Aliments fromageblanc0mg = new Aliments("Fromage blanc 0 mg","fromageblanc0mg",10);
        Aliments fromageblanc20mg = new Aliments("Fromage blanc 20 mg","fromageblanc20mg",10);
        Aliments fromagecantal = new Aliments("Fromage cantal","fromagecantal",10);
        Aliments fromagecheddar = new Aliments("Fromage cheddar","fromagecheddar",10);
        Aliments fromagedechevre = new Aliments("Fromage de chèvre","fromagedechevre",10);
        Aliments fromagegouda = new Aliments("Fromage gouda","fromagegouda",10);
        Aliments fromagemunster = new Aliments("Fromage munster","fromagemunster",10);
        Aliments fruitsausirop = new Aliments("Fruits au sirop","fruitsausirop",10);
        Aliments fruitssecsmelange = new Aliments("Fruits secs mélange","fruitssecsmelange",10);
        Aliments galantine = new Aliments("Galantine","galantine",10);
        Aliments germedeble = new Aliments("Germe de blé","germedeble",10);
        Aliments gigotdemouton = new Aliments("Gigot de mouton","gigotdemouton",10);
        Aliments gin = new Aliments("Gin","gin",10);
        Aliments ginandtonic = new Aliments("Gin and tonic","ginandtonic",10);
        Aliments gingembre = new Aliments("Gingembre","gingembre",10);
        Aliments glacealavanille = new Aliments("Glace à la vanille","glacealavanille",10);
        Aliments glaceauchocolat = new Aliments("Glace au chocolat","glaceauchocolat",10);
        Aliments glaceaucitron = new Aliments("Glace au citron","glaceaucitro",10);
        Aliments goujon = new Aliments("Goujon","goujon",10);
        Aliments goyave = new Aliments("Goyave","goyave",10);
        Aliments grainedanis = new Aliments("Graine d'anis","grainedanis",10);
        Aliments grainedecoriandre = new Aliments("Graine de coriandre","grainedecoriandre",10);
        Aliments grainedefenouil = new Aliments("Graine de fenouil","grainedefenouil",10);
        Aliments grainedepavots = new Aliments("Graine de pavots","grainedepavots",10);
        Aliments grainesdecumin = new Aliments("Graines de cumin","grainesdecumin",10);
        Aliments groseilles = new Aliments("Groseilles","groseilles",10);
        Aliments gruyere = new Aliments("Gruyère","gruyere",10);
        Aliments haddockfume = new Aliments("Haddock fumé","haddockfume",10);
        Aliments haricotsblancs = new Aliments("Haricots blancs","haricotsblancs",10);
        Aliments haricotsrouges = new Aliments("Haricots rouges","haricotsrouges",10);
        Aliments haricotssecs = new Aliments("Haricots secs","haricotssecs",10);
        Aliments haricotsverts = new Aliments("Haricots verts","haricotsverts",10);
        Aliments hareng = new Aliments("Hareng","Hareng",10);
        Aliments harengfume = new Aliments("Hareng fumé","harengfume",10);
        Aliments homard = new Aliments("Homard","homard",10);
        Aliments huiledecolza = new Aliments("Huile de colza","huiledecolza",10);
        Aliments huiledegermedeble = new Aliments("Huile de germe de blé","huiledegermedeble",10);
        Aliments huiledesoja = new Aliments("Huile de soja","huiledesoja",10);
        Aliments huledetournesol = new Aliments("Huile de tournesol","huledetournesol",10);
        Aliments huiledolive = new Aliments("Huile d'olive","huiledolive",10);
        Aliments huitres = new Aliments("huîtres","huitres",10);
        Aliments instantmasssportsystem = new Aliments("Instant mass sport system","instantmasssportsystem",10);
        Aliments jambondedinde = new Aliments("Jambon de dinde","jambondedinde",10);
        Aliments jambonmaigre = new Aliments("Jambon maigre","jambonmaigre",10);
        Aliments jaunedoeuf = new Aliments("Jaune d'oeuf","jaunedoeuf",10);
        Aliments jusdananas = new Aliments("Jus d'ananas","jusdananas",10);
        Aliments jusdecarotte = new Aliments("Jus de carotte","jusdecarotte",10);
        Aliments jusdecitron = new Aliments("Jus de citron","jusdecitron",10);
        Aliments jusdelegumecocktail = new Aliments("Jus de legume cocktail","jusdelegumecocktail",10);
        Aliments jusdepamplemousse = new Aliments("Jus de pamplemousse","jusdepamplemousse",10);
        Aliments jusdepomme = new Aliments("Jus de pomme","jusdepomme",10);
        Aliments jusderaisin = new Aliments("Jus de raisin","jusderaisin",10);
        Aliments jusdetomate = new Aliments("Jus de tomate","jusdetomate",10);
        Aliments jusdorange = new Aliments("Jus d'orange","jusdorange",10);
        Aliments kaki = new Aliments("Kaki","kaki",10);
        Aliments ketchup = new Aliments("Ketchup","ketchup",10);
        Aliments kiwi = new Aliments("Kiwi","kiwi",10);
        Aliments laitdemiecreme = new Aliments("Lait demi écrémé","laitdemiecreme",10);
        Aliments laitdesoja = new Aliments("Lait de soja","laitdesoja",10);
        Aliments laitcremeliquide = new Aliments("Lait crème liquide","laitcremeliquide",10);
        Aliments laitecremepoudre = new Aliments("Lait écrémé poudre","laitecremepoudre",10);
        Aliments laitentierliquide = new Aliments("Lait entier liquide","laitentierliquide",10);
        Aliments laitue = new Aliments("Laitue","laitue",10);
        Aliments langouste = new Aliments("Langouste","langouste",10);
        Aliments languedeboeuf = new Aliments("Langue de boeuf","languedeboeuf",10);
        Aliments lapinchasseur = new Aliments("Lapin chasseur","lapinchasseur",10);
        Aliments lapincuitencivet = new Aliments("Lapin cuit en civet","lapincuitencivet",10);
        Aliments laroscorbineeffervescente = new Aliments("La roscorbine effervescente","laroscorbineeffervescente",10);
        Aliments lentillescrues = new Aliments("Lentilles crues","lentillescrues",10);
        Aliments lentillescuites = new Aliments("Lentilles Cuites","lentillescuites",10);
        Aliments levuredebiere = new Aliments("Calamar Nature","calamarnature",10);
        Aliments lieu = new Aliments("Calamar Nature","calamarnature",10);
        Aliments lievre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments limande = new Aliments("Calamar Nature","calamarnature",10);
        Aliments liqueur = new Aliments("Calamar Nature","calamarnature",10);
        Aliments lotte = new Aliments("Calamar Nature","calamarnature",10);
        Aliments macaroni = new Aliments("Calamar Nature","calamarnature",10);
        Aliments macis = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mais = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mandarine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mangue = new Aliments("Calamar Nature","calamarnature",10);
        Aliments maquereaualapoelee = new Aliments("Calamar Nature","calamarnature",10);
        Aliments maquereauenboite = new Aliments("Calamar Nature","calamarnature",10);
        Aliments margarine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments margarineenboite = new Aliments("Calamar Nature","calamarnature",10);
        Aliments margarinetartinable = new Aliments("Calamar Nature","calamarnature",10);
        Aliments marjolaine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments marronsgrilles = new Aliments("Calamar Nature","calamarnature",10);
        Aliments martini = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mayonnaise = new Aliments("Calamar Nature","calamarnature",10);
        Aliments melon = new Aliments("Calamar Nature","calamarnature",10);
        Aliments merlantfiletnature = new Aliments("Calamar Nature","calamarnature",10);
        Aliments merlanfrit = new Aliments("Calamar Nature","calamarnature",10);
        Aliments miel = new Aliments("Calamar Nature","calamarnature",10);
        Aliments milkeggprotein = new Aliments("Calamar Nature","calamarnature",10);
        Aliments milo = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mortadelle = new Aliments("Calamar Nature","calamarnature",10);
        Aliments moulesnature = new Aliments("Calamar Nature","calamarnature",10);
        Aliments moulespreparees = new Aliments("Calamar Nature","calamarnature",10);
        Aliments moutarde = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mozarella = new Aliments("Calamar Nature","calamarnature",10);
        Aliments muesli = new Aliments("Calamar Nature","calamarnature",10);
        Aliments mures = new Aliments("Calamar Nature","calamarnature",10);
        Aliments myrtilles = new Aliments("Calamar Nature","calamarnature",10);
        Aliments navet = new Aliments("Calamar Nature","calamarnature",10);
        Aliments nectarine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments noisette = new Aliments("Calamar Nature","calamarnature",10);
        Aliments noixdecoco = new Aliments("Calamar Nature","calamarnature",10);
        Aliments noixdemuscade = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oeuf = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oeufauplat = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oeufpoche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oignon = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oignonenpoudre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oligonatalgrosesse = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oliveverte = new Aliments("Calamar Nature","calamarnature",10);
        Aliments omelette = new Aliments("Calamar Nature","calamarnature",10);
        Aliments onglet = new Aliments("Calamar Nature","calamarnature",10);
        Aliments orange = new Aliments("Calamar Nature","calamarnature",10);
        Aliments origan = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oseille = new Aliments("Calamar Nature","calamarnature",10);
        Aliments oeufbrouille = new Aliments("Calamar Nature","calamarnature",10);
        Aliments painauraisin = new Aliments("Calamar Nature","calamarnature",10);
        Aliments painblanc = new Aliments("Calamar Nature","calamarnature",10);
        Aliments paincomplet = new Aliments("Calamar Nature","calamarnature",10);
        Aliments paindepices = new Aliments("Calamar Nature","calamarnature",10);
        Aliments paindeseigle = new Aliments("Calamar Nature","calamarnature",10);
        Aliments paingrille = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pamplemousse = new Aliments("Calamar Nature","calamarnature",10);
        Aliments papaye = new Aliments("Calamar Nature","calamarnature",10);
        Aliments paprika = new Aliments("Calamar Nature","calamarnature",10);
        Aliments parmesan = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pateaugluten = new Aliments("Calamar Nature","calamarnature",10);
        Aliments patedamandes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments patedefoie = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pates = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pavedeboeuf = new Aliments("Calamar Nature","calamarnature",10);
        Aliments peche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments perche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments perrier = new Aliments("Calamar Nature","calamarnature",10);
        Aliments persil = new Aliments("Calamar Nature","calamarnature",10);
        Aliments persilseche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments petitspois = new Aliments("Calamar Nature","calamarnature",10);
        Aliments petitsuisse = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pieuvrepoulpe = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pimentenpoudre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pissenlit = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pizzajambonfromage = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poire = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poireau = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poiresausiropleger = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poiresausiropsucree = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poischiche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivreblanc = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivredejamaique = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivrenoir = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivrerouge = new Aliments("Calamar Nature","calamarnature",10);
        Aliments poivron = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pomme = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pommedeterre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments popcorn = new Aliments("Calamar Nature","calamarnature",10);
        Aliments portsalut = new Aliments("Calamar Nature","calamarnature",10);
        Aliments prairectustace = new Aliments("Calamar Nature","calamarnature",10);
        Aliments protiplus = new Aliments("Calamar Nature","calamarnature",10);
        Aliments prune = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pruneau = new Aliments("Calamar Nature","calamarnature",10);
        Aliments pucnh = new Aliments("Calamar Nature","calamarnature",10);
        Aliments quakeroats = new Aliments("Calamar Nature","calamarnature",10);
        Aliments radis = new Aliments("Calamar Nature","calamarnature",10);
        Aliments ragoutdeboeuf = new Aliments("Calamar Nature","calamarnature",10);
        Aliments raie = new Aliments("Calamar Nature","calamarnature",10);
        Aliments raisin = new Aliments("Calamar Nature","calamarnature",10);
        Aliments raisinsec = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rhum = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rilettes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments risthymus = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rizblanc = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rizcomplet = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rognondeboeuf = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rognondeveau = new Aliments("Calamar Nature","calamarnature",10);
        Aliments romarinseche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments roquefort = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rotidedinde = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rotideveau = new Aliments("Calamar Nature","calamarnature",10);
        Aliments roussette = new Aliments("Calamar Nature","calamarnature",10);
        Aliments rumsteak = new Aliments("Calamar Nature","calamarnature",10);
        Aliments safran = new Aliments("Calamar Nature","calamarnature",10);
        Aliments safrandesindes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments salademais = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saladedethon = new Aliments("Calamar Nature","calamarnature",10);
        Aliments salsifis = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sandwichjambonbeurre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sandwichjambonfromage = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sardine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sardinesalhuile = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saucesalade = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saucespaghettis = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saucetomate = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saucissedefrancfort = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saucissonsec = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sauge = new Aliments("Calamar Nature","calamarnature",10);
        Aliments saumon = new Aliments("Calamar Nature","calamarnature",10);
        Aliments seiche = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sel = new Aliments("Calamar Nature","calamarnature",10);
        Aliments selegerme = new Aliments("Calamar Nature","calamarnature",10);
        Aliments semouledeble = new Aliments("Calamar Nature","calamarnature",10);
        Aliments semouledemais = new Aliments("Calamar Nature","calamarnature",10);
        Aliments seniorssimplexvitall = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sojafarine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sojagraine = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sole = new Aliments("Calamar Nature","calamarnature",10);
        Aliments soupeauxchampignons = new Aliments("Calamar Nature","calamarnature",10);
        Aliments soupelegumes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments soupeminestorne = new Aliments("Calamar Nature","calamarnature",10);
        Aliments spaghettis = new Aliments("Calamar Nature","calamarnature",10);
        Aliments steackaloyau = new Aliments("Calamar Nature","calamarnature",10);
        Aliments steackhache = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sucreblanc = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sucrebrun = new Aliments("Calamar Nature","calamarnature",10);
        Aliments sucreenpoudre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments supercomplexvitall = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tapioca = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tarteauxcerises = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tarteauxfraises = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tarteauxpommes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments the = new Aliments("Calamar Nature","calamarnature",10);
        Aliments thoncru = new Aliments("Calamar Nature","calamarnature",10);
        Aliments thonenboite = new Aliments("Calamar Nature","calamarnature",10);
        Aliments thymfrais = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tomate = new Aliments("Calamar Nature","calamarnature",10);
        Aliments tripes = new Aliments("Calamar Nature","calamarnature",10);
        Aliments truitedemer = new Aliments("Calamar Nature","calamarnature",10);
        Aliments truiteplat = new Aliments("Calamar Nature","calamarnature",10);
        Aliments turbot = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vichystyorre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vinaigre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vinrose = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vinrouge = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vittelgrandesource = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vittelhepard = new Aliments("Calamar Nature","calamarnature",10);
        Aliments vodka = new Aliments("Calamar Nature","calamarnature",10);
        Aliments volvic = new Aliments("Calamar Nature","calamarnature",10);
        Aliments whisky = new Aliments("Calamar Nature","calamarnature",10);
        Aliments yaourtbifidusactif = new Aliments("Calamar Nature","calamarnature",10);
        Aliments yaourtbulgare = new Aliments("Calamar Nature","calamarnature",10);
        Aliments yaourtmaigre = new Aliments("Calamar Nature","calamarnature",10);
        Aliments yaourtnature = new Aliments("Calamar Nature","calamarnature",10);
        Aliments yoplaitauxfruits = new Aliments("Calamar Nature","calamarnature",10);








        list.add(ail);
        list.add(ailenpoudre);
        list.add(amendesblanchiessechees);
        list.add(amandessechees);
        list.add(anethfraiche);
        list.add(anethsechee);
        list.add(aromedevanille);
        list.add(aromedevanillealcool);
        list.add(asperges);
        list.add(aubergine);
        list.add(avocat);
        list.add(bacon);
        list.add(baguette);
        list.add(banane);
        list.add(bananesechee);
        list.add(barloup);
        list.add(basilicfinesherbes);
        list.add(basilicfrais);
        list.add(betaselen);
        list.add(betteraverouge);
        list.add(beurre);
        list.add(biereblonde);
        list.add(biereordinaire);
        list.add(bifteckboeuf);
        list.add(bifteckcheval);
        list.add(bigmac);
        list.add(bigorneau);
        list.add(biscotte);
        list.add(biscuitsable);
        list.add(blancdepoulet);
        list.add(blancdoeuf);
        list.add(boudinblanc);
        list.add(boudinnoir);
        list.add(bouillondevolaille);
        list.add(brie);
        list.add(brochet);
        list.add(cabillaud);
        list.add(cacahuettes);
        list.add(cafefiltre);
        list.add(cafenescafe);
        list.add(cafenescafe1tasse);
        list.add(caille);
        list.add(cake);
        list.add(calamarfrit);
        list.add(calamarnature);
        list.add(camambert);
        list.add(canardroti);
        list.add(cannelle);
        list.add(capresenboite);
        list.add(cardamome);
        list.add(carencyl);
        list.add(carotte);
        list.add(carpe);
        list.add(carrelet);
        list.add(casis);
        list.add(caviar);
        list.add(celerifeuille);
        list.add(celeriracine);
        list.add(cerealescropsyfruit);
        list.add(cerealesnature);
        list.add(cerfeuille);
        list.add(cerises);
        list.add(chairasaucisse);
        list.add(champagne);
        list.add(champignons);
        list.add(charlottegateau);
        list.add(chataignefraiche);
        list.add(chevalroti);
        list.add(chocapic);
        list.add(chocolatacroquer);
        list.add(chocolataulait);
        list.add(chocolatenpoudre);
        list.add(choucroutte);
        list.add(choucru);
        list.add(choufleur);
        list.add(chouxdebruxelles);
        list.add(chrome);
        list.add(ciboulettecrue);
        list.add(ciboulettelyophilisee);
        list.add(citronjaune);
        list.add(citronvert);
        list.add(citrouille);
        list.add(clousdegirofle);
        list.add(cocacola);
        list.add(cocacolacanette);
        list.add(coeurdeboeuf);
        list.add(coing);
        list.add(colinmerlu);
        list.add(concombre);
        list.add(coneglacecreme);
        list.add(confiture);
        list.add(congrepoisson);
        list.add(contrexeville);
        list.add(coquillestjacques);
        list.add(cornflakes);
        list.add(cornichon);
        list.add(cotedagneau);
        list.add(cotedeboeufrotie);
        list.add(cotelettedeporc);
        list.add(courgettes);
        list.add(couscous);
        list.add(crabechair);
        list.add(cremechantilly);
        list.add(cremedasperges);
        list.add(cremefraiche);
        list.add(cresson);
        list.add(crevette);
        list.add(croissant);
        list.add(cuissedegrnouille);
        list.add(cuissepouletroti);
        list.add(cumin);
        list.add(curry);
        list.add(daiquiri);
        list.add(dattes);
        list.add(dorade);
        list.add(echalote);
        list.add(echalotelyophilisees);





        return list;
    }

}